---
- name: 001_practice_task_001
  hosts: all


  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present

  - name: check hhtpd is running
    service:
      name: httpd
      state: started

  - name: create /var/www/html/index.html with “Welcome to my web server”
    lineinfile:
      path: /var/www/html/index.html
      line: 'Welcome to my web server'
      state: present
      create: yes

  - name: Open port tcp/80
    firewalld:
      service: http
      permanent: true
      state: enabled
   
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted 
...
