---
- name: 003_practice_task_001
  hosts: all


  tasks:
    - name: /etc/default/grub changing
      lineinfile:
        path: /etc/default/grub
        backrefs: yes
        regexp: "GRUB_CMDLINE_LINUX=.*"
        line: 'GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/cs-swap rd.lvm.lv=cs/root rd.lvm.lv=cs/swap rhgb quiet net.ifnames=0 biosdevname=0"'


    - name: Write grub configuration file
      command: grub2-mkconfig -o /etc/default/grub 
       
     
